---
sbt_version: "0.13.12"
sbt_archive_name: "sbt-{{sbt_version}}"
sbt_archive_file: "{{sbt_archive_name}}.tgz"
sbt_download_url: "https://dl.bintray.com/sbt/native-packages/sbt/{{sbt_version}}/{{sbt_archive_file}}"

sbt_lib_path: "/usr/share/sbt"
sbt_lib_path_target: "{{sbt_lib_path}}/{{sbt_version}}"
sbt_link_target: "/usr/bin/sbt"
...