---
- name: Configure Linux 7 generic Java box with Apache Kafka demo
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes
  vars_files:
    - kafka-vars.yml

  roles:
    - role: common
    - role: jdk
    - role: scala
    - role: sbt
...