---
- name: Create lib dir
  file:
    path: '{{ sbt_lib_path_target }}'
    state: directory
    recurse: yes

- name: Download sbt v{{sbt_version}}
  get_url:
    url: '{{sbt_download_url}}'
    dest: '/tmp/{{ sbt_archive_file }}'

- name: Unpack sbt
  unarchive:
    src: '/tmp/{{ sbt_archive_file }}'
    dest: '{{ sbt_lib_path_target }}'
    copy: no

- name: Link sbt
  file:
    src: '{{ sbt_lib_path_target }}/sbt/bin/sbt'
    state: link
    dest: '{{ sbt_link_target }}'
...